### ISSUE TITLE
GSoC Workspace (2025): Virtual filesystem security for WasmEdge plug-ins with exporting WASI APIs

### ISSUE THREAD

**Issue by grorge123** [WasmEdge/WasmEdge#4131]
### Summary

This GSOC project aims to enhance the security of WasmEdge plug-ins by exporting key WASI APIs, thereby ensuring a robust and secure virtual filesystem sandbox for file operations. 

### Details

With the rapid growth of AI applications, WasmEdge plug-ins have become indispensable for tasks such as natural language processing, image synthesis, and speech recognition. However, direct file system access in current implementations exposes critical security risks. To address this, our proposal focuses on designing and implementing a dedicated filesystem sandbox API that restricts file read/write operations to pre-authorized directories. The initial phase will concentrate on the WASI-NN plug-in and other simpler file I/O functions, with potential future enhancements to more complex applications like Stable Diffusion’s image-loading functionality.
Our comprehensive plan includes an in-depth study of the WasmEdge sandbox architecture, API design and integration, modification of internal plugin call patterns, and the development of rigorous test cases to validate sandbox effectiveness. Detailed documentation and developer guidelines will be prepared to facilitate secure plugin development. With a project timeline from June 2 to September 1, this initiative will leverage my background in virtualization, parallel computing and my past contributions to WasmEdge. The expected outcome is a significant improvement in the security and isolation of file operations in WasmEdge plug-ins, paving the way for safer and more reliable deployment of AI-driven applications.

### Milestone

- Research and Analysis (June 2 – June 16)
  - [x] Study the WasmEdge sandbox filesystem architecture and understand the underlying code.
  Analyze current file I/O implementations in plugins (e.g., WASI-NN).
- API Design (June 17 – June 30)
  - [x] Design the filesystem sandbox API based on the insights gained during the research phase.
  - [ ] Document the API design and create design proposals.
- Implementation (July 1 – July 27)
  - [x] Integrate the new API into WasmEdge by exposing it via Plugin.h.
  - [x] Modify internal plugin call patterns to replace native C++ file I/O calls with the new API.
- Testing and Debugging (July 28 – August 11)
  - [x] Develop and execute comprehensive test cases, including attempts to access unauthorized directories 
- Documentation and Developer Guidance (August 12 – September 1)
  - [ ] Write detailed documentation for the new API, including usage examples and integration guidelines.

### Appendix

[GSOC issue](https://github.com/WasmEdge/WasmEdge/issues/4012)

**Comment by q82419** [comment]
You can follow the current working branch `dev/wasi_vfs`.
You can add the functions you implemented and create PR merging into that branch. Thanks!

**Comment by grorge123** [comment]
This week, I traced the WasmEdge codebase. I found that the Environ class provides fdRead and fdWrite functions. I plan to use it to implement the low-level implement of the API.
I found that most of the file read/write operations used C++ std::iostream, so I decided to design the new API to have a similar interface to the iostream, such that we can directly change the type to replace all the plugins implemented.

Based on the above plan, I have a question. In order to let the plugin call the API, We need to pass the Environ to a plugin or something similar method to let we can access the Environ class. Do we need to modify the plugin register to pass the Environ class, or do you have other suggestions?

**Comment by q82419** [comment]
> This week, I traced the WasmEdge codebase. I found that the Environ class provides fdRead and fdWrite functions. I plan to use it to implement the low-level implement of the API. I found that most of the file read/write operations used C++ std::iostream, so I decided to design the new API to have a similar interface to the iostream, such that we can directly change the type to replace all the plugins implemented.
> 
> Based on the above plan, I have a question. In order to let the plugin call the API, We need to pass the Environ to a plugin or something similar method to let we can access the Environ class. Do we need to modify the plugin register to pass the Environ class, or do you have other suggestions?

You can trace the changes on `dev/wasi_vfs` branch.
I added the `getWASIModule()` function in `CallingFrame` class, and binded the WASI module into the WASM module when instantiating.
The plug-in functions will be invoked as a host function from a WASM function. Like accessing the WASM memory via `CallingFrame`, you can get the WASI module from `CallingFrame` via the `getWASIModule()` function.
You can modify or add some user-friendly APIs to `CallingFrame` for the plug-ins to use the WASI.

**Comment by grorge123** [comment]
I created PR #4181 to get `Environ` from `callingframe` and store `Environ` pointer in `WASIEnviron`, such that we can use `Environ` in the plugin function.
Since the WASIModule is const, we will use `const_cast` to remove constness, and then we can directly call the read/write function in the `Environ` function.

**Comment by grorge123** [comment]
I pushed to the wrong remote, such that it closed the previous PR. I have reopened a new PR #4197.
This week, I finished the basic IO stream implementation. So I expected that we could replace all the std IO streams with our WasmEdge IO stream. I will use an example to test the functionality next week.

**Comment by grorge123** [comment]
This week, I have tried to replace the original IO stream with the WasmEdge IO stream in the MLX backend. It can work in some cases, but it has a segmentation fault in the CI test. I will trace it next week and fix it.

**Comment by grorge123** [comment]
I found that the test unit does not run the WASM module, such that we have no WASM filesystem. So, I changed the implementation, directly using the C++ IO API when the module is not a WASM module.
Currently, I have modified mlx, ggml, and whisper plugins to use the WasmEdge IO API.

**Comment by grorge123** [comment]
I fixed the review changes this week.
We planned to modify the internal plugin call in the implementation part. We have integrated the wasi-nn plugin now.
But there are some plugins that use other API instead of STD IO to read/write files.
1. sd_func.cpp use stbi_write_png
2. opencvmini_func.cpp use imdecode
3. ocr_func.cpp use pixRead
4. avformat_func.cpp use avio

I want to confirm whether we should continue to integrate those plugins, or we can continue to the next parts first, which involves writing the unit test to test the current WasmEdge IO.

**Comment by hydai** [comment]
Let's focus on writing the unit tests for WasmEdge IO first.

**Comment by grorge123** [comment]
I fixed the new review changes this week. Rename the class and move the file.
I have added some basic unit tests this week. There are still some test cases I have not covered, and I found that I have some error-handling problems that need to be fixed. I will fix it and add more tests in the next week.

**Comment by q82419** [comment]
> I fixed the review changes this week. We planned to modify the internal plugin call in the implementation part. We have integrated the wasi-nn plugin now. But there are some plugins that use other API instead of STD IO to read/write files.
> 
> 1. sd_func.cpp use stbi_write_png
> 2. opencvmini_func.cpp use imdecode
> 3. ocr_func.cpp use pixRead
> 4. avformat_func.cpp use avio
> 
> I want to confirm whether we should continue to integrate those plugins, or we can continue to the next parts first, which involves writing the unit test to test the current WasmEdge IO.

After the unit tests, you can apply all plug-ins with the vfs mechanism.
Rather than the stdio, I think maybe you can design a series of API for checking the r/w permissions with file paths?
Therefore after the checking with the vfs APIs, developers can use the other APIs to r/w files, and we can claim that it's plugin developers' responsibility to use the vfs API to check the r/w permission before they accessing files directly.

**Comment by grorge123** [comment]
I added more unit tests to cover other read and write functions. And I created a new API to check if the file exists. I will trace how to get the file permissions next week.

**Comment by grorge123** [comment]
I added some functions to let developers check if the file exists and can be read or written.
Can we try to merge to the master branch in the next week? I am not sure if there are some problems that happen when we run all the CI tests.

**Comment by hydai** [comment]
Sounds good. @q82419 Please do a review, and I think we can try to create a new PR to the master branch to check compatibility.

**Comment by grorge123** [comment]
This week, I fixed the review change. I store the callingframe to Env, such that we call get Environ from the callingframe in each function call. And I moved the functions about file permission checking to the Environ class.

**Comment by q82419** [comment]
> Sounds good. [@q82419](https://github.com/q82419) Please do a review, and I think we can try to create a new PR to the master branch to check compatibility.

I still have some suggestions. I'll comment in these days. Thanks!

**Comment by hydai** [comment]
The PR #4340 has been merged into the master branch. All milestones in this issue are completed. Closing it.
